CREATE TABLE book (
	bookId INT(16) UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	authorId INT(16) UNSIGNED NOT NULL
);

ALTER TABLE book ADD CONSTRAINT bookAuthorConstraint FOREIGN KEY (authorId) REFERENCES author(`id`) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE bookMeta (
	bookId INT(16) UNSIGNED NOT NULL,
	lang VARCHAR(8) NOT NULL,
	title VARCHAR(128) NOT NULL,
	shortDescription VARCHAR(160), 
	longDescription LONGTEXT,
	PRIMARY KEY(bookId, lang)
);

ALTER TABLE bookMeta ADD CONSTRAINT bookMetaBookIdConstraint FOREIGN KEY (bookId) REFERENCES book(`bookId`) ON UPDATE CASCADE ON DELETE CASCADE;